if (WINDOWS_RENDER_SYSTEM STREQUAL "vulkan")
    set(APPEND PLATFORM_REQUIRED_DEPS Vulkan)
    set(APP_RENDER_SYSTEM vulkan)
else()
    message(SEND_INFO "Render System: Defaulting to dx11")
    set(APPEND PLATFORM_REQUIRED_DEPS D3DX11Effects)
    set(APP_RENDER_SYSTEM dx11)
endif()
